repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: autoflake
        name: autoflake
        exclude: .*/__init__.py
        entry: poetry run autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --expand-star-imports
          - --remove-duplicate-keys
          - --remove-unused-variables
        language: system
        types: [ python ]
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [ python ]
      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        types: [ python ]
      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        types: [ python ]
      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        types: [ python ]
